version: "3.8"

services:
  fiware-dashboard:
    image: kamisama157/fiware-dashboard:latest
    container_name: fiware_dashboard
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
